/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        ground: '#0B0E14',
        surface: '#111620',
        'surface-raised': '#16202F',
        'border-color': '#1E2A3A',
        'border-subtle': '#151E2B',
        'text-primary': '#E8EBF0',
        'text-secondary': '#8B97A8',
        'text-muted': '#4A5568',
        'text-inverse': '#0B0E14',
        accent: '#2DD4BF',
        'accent-dim': '#0D9488',
        'accent-subtle': 'rgba(13,148,136,0.15)',
        'layer-foundational': '#6366F1',
        'layer-infra': '#3B82F6',
        'layer-operational': '#2DD4BF',
        'layer-translational': '#F59E0B',
        warning: '#F59E0B',
        'warning-dim': '#92400E',
        deployed: '#10B981',
        bainbridge: '#F59E0B',
        cir: '#2DD4BF',
        rsps: '#6366F1',
        'ce-ledger': '#3B82F6',
        delta: '#8B5CF6',
        sovereign: '#EC4899',
        premise: '#6B7280',
      },
      fontFamily: {
        display: ["'DM Serif Display'", 'Georgia', 'serif'],
        body: ["'DM Sans'", 'system-ui', 'sans-serif'],
        mono: ["'Fira Code'", "'Courier New'", 'monospace'],
      },
      maxWidth: {
        container: '1200px',
        'container-narrow': '800px',
        'container-wide': '1400px',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
      spacing: {
        'space-1': '0.25rem',
        'space-2': '0.5rem',
        'space-3': '0.75rem',
        'space-4': '1rem',
        'space-6': '1.5rem',
        'space-8': '2rem',
        'space-12': '3rem',
        'space-16': '4rem',
        'space-24': '6rem',
        'space-32': '8rem',
      },
    },
  },
  plugins: [],
};
